<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>acadbot_bringup</name>
  <version>1.0.0</version>
  <description>Top-level convenience launch files for the AcadBot SLAM track.</description>
  <maintainer email="wael.alsayegh@inmind.ai">Wael Al Sayegh</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>acadbot_description</exec_depend>
  <exec_depend>acadbot_gazebo</exec_depend>
  <exec_depend>acadbot_slam</exec_depend>
  <exec_depend>acadbot_navigation</exec_depend>
  <exec_depend>acadbot_control</exec_depend>
  <exec_depend>acadbot_courier</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>teleop_twist_keyboard</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
